repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: no-commit-to-branch
    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
      verbose: false
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: check-executables-have-shebangs
    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]
      verbose: false
    # Security
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key
